// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://vetbpnxvpyzvihsgtcak.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZldGJwbnh2cHl6dmloc2d0Y2FrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2MTMyNjIsImV4cCI6MjA3MzE4OTI2Mn0.6pYsRUZngFM33OvY1RjbTH3IGItykmKX62PxsJ6Bpes";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
